clear all;
close all;
load x.txt;
load y.txt;
plot(x,y,'k',x',y','k');
axis equal;
print -djpeg grid.jpg;
%print -depsc2 grid.eps;

clear all;
close all;
load errVal.txt;
load h_eff.txt;
h1=loglog(h_eff,errVal,'r-');
hold on;
hsquared=h_eff.^2;
h2=loglog(h_eff,hsquared,'k--');
ylabel('max error');
xlabel('effective h');
legend([h1,h2],'max err','h^2','Location','SouthEast');
axis equal;
print -djpeg max.jpg;
%print -depsc2 max.eps;
